name: vision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - jupyter=1.0.0
  - pip
  - pip:
    - opencv-python==4.8.0.76
    - pillow==10.0.0
